plugins:
  - jest
env:
  es2022: true
  node: true
  jest: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:jest/recommended
ignorePatterns:
  - dist/
  - coverage/
  - __fixtures__/
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.eslint.json'
rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle:
    - error
    - allow:
      - __filename
      - __dirname
